In [105]:



import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
import os;
import csv


os.chdir('/Users/talbotm/Documents/PythonProjects/')
print(os.getcwd())

# d = {}
# d[1] = [22, 33, 44]
# d[2] = [55,66,77]

# for key, value in d.items():
#     print(value[1])


data = csv.reader('x1.csv')  
    
print(data)   

x = np.array([1,2,3,4,5,5,6, 7, 8,9 ,10])
y = np.array([1,-2,3,4,5,5,6, 7, 8,9 ,10])

x = x.reshape(-1,1)
y = y.reshape(-1,1)

# # Create linear regression object
regr = linear_model.LinearRegression()

# # Train the model using the training sets
regr.fit(x, y)


print(x)
print(y)

print('Coefficients: \n', regr.coef_)
print('Intercept: \n', regr.intercept_ )
#The mean square error
print("Residual sum of squares: %.2f"
      % np.mean((regr.predict(x) - y) ** 2))
# Explained variance score: 1 is perfect prediction
print('r^2: %.2f' % regr.score(x, y))






#csv.reader(csvfile, dialect='excel', **fmtparams)


/Users/talbotm/Documents/PythonProjects
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1]
 [-2]
 [ 3]
 [ 4]
 [ 5]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Coefficients: 
 [[ 1.16703297]]
Intercept: 
 [-1.27472527]
Residual sum of squares: 1.11
r^2: 0.90


In [85]:
import os
import csv
import sys


os.chdir('/Users/talbotm/Documents/PythonProjects/Jupyter/')
print(os.getcwd())


# import csv
# with open('x1.csv', 'r') as f:
#     reader = csv.reader(f)
#     for row in reader:
#         print(row)
        
import pandas as pd

data = pd.read_csv('x1.csv')




        

/Users/talbotm/Documents/PythonProjects/Jupyter
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: x, dtype: int64


In [115]:
## Read csv file with two columns and compute regression 

import os
import csv
import sys
import pandas as pd

os.chdir('/Users/talbotm/Documents/PythonProjects/Jupyter/')
print(os.getcwd())

data = pd.read_csv('x1.csv')

data.x = list(data.x)
data.y = list(data.y)

x = (data.x.reshape(-1,1))
y = (data.y.reshape(-1,1))


# # Create linear regression object
regr = linear_model.LinearRegression()

# # Train the model using the training sets
regr.fit(x, y)


print('Coefficients: \n', regr.coef_)
print('Intercept: \n', regr.intercept_ )
#The mean square error
print("Residual sum of squares: %.2f"
      % np.mean((regr.predict(x) - y) ** 2))
# Explained variance score: 1 is perfect prediction
print('r^2: %.2f' % regr.score(x, y))





/Users/talbotm/Documents/PythonProjects/Jupyter
Coefficients: 
 [[ 1.05454545]]
Intercept: 
 [ 0.6]
Residual sum of squares: 0.07
r^2: 0.99


0    1
1    2
2    3
3    4
dtype: int64

In [116]:
a = pd.Series([1,2,3,4])
b = a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [130]:
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
...                'B': {0: 1,   1: 3,   2: 5},
...                'C': {0: 2,   1: 4,   2: 6}})
df[]

A  B  C
0  a  1  2